### ISSUE TITLE
[2.0] Prefetch click triggers visit on secondary button mouseup

### ISSUE THREAD

**Issue by ChrisB-TL** [inertiajs/inertia#2185]
### Version:

- `@inertiajs/vue3` version: 2.0.0

### Describe the problem:

When using prefetch="click", the visit is triggered on mouse up of the secondary mouse button (e.g. user is attempting to access context menu) - making it impossible to e.g. open in new tab without triggering a visit in the current window.

I cannot think of a scenario where the intent behind a secondary button press would be a visit in the same window (i.e. will always be new tab, new window, etc.), so we could probably just ignore any MouseEvent where MouseEvent.button === 2 (or possibly where MouseEvent.button !== 0).

I have only tested w/ Vue3, but it looks like this behavior is common to all adapters.

### Steps to reproduce:

`<Link href="/" prefetch="click">I shouldn't be visited when clicked with secondary</Link>`

**Comment by joetannenbaum** [comment]
I'm unable to replicate this in `v2.0.2` which back ported fixes this these from `v1.3.0`. Can you confirm this is fixed in the latest version?

**Comment by ChrisB-TL** [comment]
Hi Joe

Have upgraded to v2.0.2 and have the same issue. Have noticed in the process of trying to debug, you get the same result when clicking a Link with "select component on page" in Chrome Vue devtools.

I'll try and reproduce in a clean repo and circle back with it if I still get the same.

Cheers

Chris

**Comment by ChrisB-TL** [comment]
Hi @joetannenbaum 

Have reproduced on the navbar of the welcome page on a [fresh install of Breeze](https://github.com/[ChrisB-TL/inertia-prefetch](https://github.com/ChrisB-TL/inertia-prefetch)) (with the nav bar Links changed to prefetch="click").

I've tested on Chrome and Edge, both on Windows. Don't have access to a Mac to check.

Cheers

Chris

**Comment by ChrisB-TL** [comment]
Huh! How bizarre. Thanks for looking into Joe.

**Comment by MatasElectronics** [comment]
We've encountered a very similar problem recently where links with `prefetch="click"` will misbehave when you try to do a `ctrl + click` or `cmd + click` or middle mouse button click or something, to open the link in a new tab. 

If you try this, as soon as you release the mouse button, it will both open a new tab to the clicked page, but will also navigate the current tab to that page.

This is only when using `prefetch="click"` and not when using just `prefetch`.
