### ISSUE TITLE
Deferred props overwrite existing errors prop after redirect

### ISSUE THREAD

**Issue by travisricks** [inertiajs/inertia#2302]
## Versions

- `@inertiajs/core`: `2.0.6`  
- `@inertiajs/vue3`: `2.0.6`  
- php `inertiajs/inertia-laravel`: `2.x-dev`

---

## Describe the problem

When using deferred shared props via `Inertia::defer()`, any errors that occure from the initial `POST` response (e.g. validation errors) are **silently removed** after the deferred prop is loaded in a second XHR request.

This causes the following issue:

1. A user submits a form (e.g. via `router.post(...)`)
2. The server returns a `302` redirect with `withErrors(...)`
3. The redirected page’s initial XHR response includes the `errors` object in `page.props` ✅
4. Then, Inertia automatically loads the deferred prop in a second XHR request
5. That second response does **not include `errors`**, so the `errors` prop on the page is **wiped out** ❌

This results in `form.errors` or `usePage().props.errors` being cleared **before the user has a chance to see them**.

I was expecting Inertia to **preserve non-deferred props like `errors`** when merging a deferred prop response. Am I misunderstanding how deferred props are intended to work?

---

## Steps to reproduce

1. Define a deferred prop in your page controller:

   ```php
   Inertia::render('MyPage', [
       'nonDeferredProp' => 'foo',
       'deferredProp' => Inertia::defer(fn () => $some_deferred_value),
   ]);

1. From the frontend, make a POST request that will trigger a validation error:

   ```javascript
   router.post(
     route('a.post.endpoint'),
     { payload }
   );
   ```

1. Observe the following network requests:
   - POST request → 302 redirect
   - First GET (XHR) to /page → includes errors, but not deferredProp
   - Second GET (XHR) for deferred prop → includes deferredProp, but omits errors

As a result, errors are removed from the final page.props.

**Comment by HichemTab-tech** [comment]
Hello @travisricks , the `errors` prop is shared via `Inertia::share`, giving us limited control. I recommend using `form.post` instead of `router.post` as it automatically handles and preserves the `errors` object, even when the prop is reset.

Alternatively, modifying [`src/Middleware.php`](https://github.com/inertiajs/inertia-laravel/blob/32e80145ae36e89742b90a654ec482911a0bd1b7/src/Middleware.php#L56) in [inertia-laravel](https://github.com/inertiajs/inertia-laravel) as follows:

```diff
public function share(Request $request)
{
    return [
-        'errors' => Inertia::always($this->resolveValidationErrors($request)),
+        'errors' => fn () => ($this->resolveValidationErrors($request)),
    ];
}
```

would prevent errors from being included in partial reloads. However, I'm unsure if this change is safe and warrants a pull request. We should seek feedback from other people before proceeding.

In the meantime, using `form.post` should resolve the issue.

**Comment by travisricks** [comment]
@HichemTab-tech 
Thanks for the info, I'll give it a try.

**Comment by travisricks** [comment]
@HichemTab-tech 
Turns out my initial solution wasn’t actually working — I had mistakenly commented out the deferred prop on the backend and was testing with props that were already included in the initial payload. Once I re-enabled the deferred prop, the errors object no longer persisted after the deferred props xhr call was made, even when using the Inertia form helper.

If anyone has ideas or suggestions on this, I’d really appreciate the input!

**Comment by bretto36** [comment]
We are also facing this same issue. We have a PUT request that loads on a page, when the put request fails with vaildation errors, the page is reloaded, then the deferred props on that page are loaded, and the validation errors disappear. We have removed the deferred prop and everything works fine. 

I have tried the HandleInertiaRequests suggestion above and that does NOT fix it. 

We have tried to debug but can't seem to figure out how they are disappearing after a defer load
